parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Kernel.php'

    PDO:
        class: PDO
        factory: ['App\Infrastructure\PdoFactory', 'create']
        arguments:
            $dsn: '%env(DB_DSN)%'
            $user: '%env(DB_USER)%'
            $password: '%env(DB_PASSWORD)%'
